twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        imef_url: '%imef_url%'
        app_view: '%app_view%'

when@test:
    twig:
        strict_variables: true
